

from dbd_perks.killer_perk_names import KILLER_PERK_NAMES


TIER_1_BANNED_SURVIVOR_PERKS = []

TIER_1_BANNED_SURVIVOR_PERK_COMBOS = []

TIER_1_BANNED_KILLER_PERKS = [
    KILLER_PERK_NAMES.NO_HOLDS_BARRED,
    KILLER_PERK_NAMES.GRIM_EMBRACE,
    KILLER_PERK_NAMES.SCOURGE_HOOK_PAIN_RESONANCE
]

TIER_1_BANNED_KILLER_PERK_COMBOS = []