







from dbd_perks.survivor_perk_names import SURVIVOR_PERK_NAMES


TIER_5_BANNED_SURVIVOR_PERKS = [
    SURVIVOR_PERK_NAMES.ADRENALINE,
    SURVIVOR_PERK_NAMES.BALANCED_LANDING,
    SURVIVOR_PERK_NAMES.BITE_THE_BULLET,
    SURVIVOR_PERK_NAMES.BOTANY_KNOWLEDGE,
    SURVIVOR_PERK_NAMES.BUCKLE_UP,
    SURVIVOR_PERK_NAMES.CHAMPION_OF_LIGHT,
    SURVIVOR_PERK_NAMES.CLEAN_BREAK,
    SURVIVOR_PERK_NAMES.DEAD_HARD,
    SURVIVOR_PERK_NAMES.DECISIVE_STRIKE,
    SURVIVOR_PERK_NAMES.DELIVERANCE,
    SURVIVOR_PERK_NAMES.DESPERATE_MEASURES,
    SURVIVOR_PERK_NAMES.DO_NO_HARM,
    SURVIVOR_PERK_NAMES.DUTY_OF_CARE,
    SURVIVOR_PERK_NAMES.EMPATHIC_CONNECTION,
    SURVIVOR_PERK_NAMES.FINESSE,
    SURVIVOR_PERK_NAMES.FOR_THE_PEOPLE,
    SURVIVOR_PERK_NAMES.HOPE,
    SURVIVOR_PERK_NAMES.INNER_FOCUS,
    SURVIVOR_PERK_NAMES.INNER_STRENGTH,
    SURVIVOR_PERK_NAMES.LEADER,
    SURVIVOR_PERK_NAMES.LIGHTWEIGHT,
    SURVIVOR_PERK_NAMES.LITHE,
    SURVIVOR_PERK_NAMES.MADE_FOR_THIS,
    SURVIVOR_PERK_NAMES.OVERCOME,
    SURVIVOR_PERK_NAMES.PLOT_TWIST,
    SURVIVOR_PERK_NAMES.POISED,
    SURVIVOR_PERK_NAMES.PREMONITION,
    SURVIVOR_PERK_NAMES.RAPID_RESPONSE,
    SURVIVOR_PERK_NAMES.REACTIVE_HEALING,
    SURVIVOR_PERK_NAMES.RESILIENCE,
    SURVIVOR_PERK_NAMES.RESURGENCE,
    SURVIVOR_PERK_NAMES.ROOKIE_SPIRIT,
    SURVIVOR_PERK_NAMES.SECOND_WIND,
    SURVIVOR_PERK_NAMES.SELF_CARE,
    SURVIVOR_PERK_NAMES.SMASH_HIT,
    SURVIVOR_PERK_NAMES.SOLIDARITY,
    SURVIVOR_PERK_NAMES.SOUL_GUARD,
    SURVIVOR_PERK_NAMES.SPINE_CHILL,
    SURVIVOR_PERK_NAMES.SPRINT_BURST,
    SURVIVOR_PERK_NAMES.STRENGTH_IN_SHADOWS,
    SURVIVOR_PERK_NAMES.UNBREAKABLE,
    SURVIVOR_PERK_NAMES.WELL_MAKE_IT,
    SURVIVOR_PERK_NAMES.WERE_GONNA_LIVE_FOREVER
]

TIER_5_BANNED_SURVIVOR_PERK_COMBOS = []