

from dbd_perks.killer_perk_names import KILLER_PERK_NAMES
from dbd_perks.survivor_perk_names import SURVIVOR_PERK_NAMES


TIER_2_BANNED_SURVIVOR_PERKS = [
    SURVIVOR_PERK_NAMES.BOTANY_KNOWLEDGE,
    SURVIVOR_PERK_NAMES.DEAD_HARD,
    SURVIVOR_PERK_NAMES.DECISIVE_STRIKE,
    SURVIVOR_PERK_NAMES.DELIVERANCE,
    SURVIVOR_PERK_NAMES.DO_NO_HARM,
    SURVIVOR_PERK_NAMES.DUTY_OF_CARE,
    SURVIVOR_PERK_NAMES.FINESSE,
    SURVIVOR_PERK_NAMES.MADE_FOR_THIS,
    SURVIVOR_PERK_NAMES.OVERCOME,
    SURVIVOR_PERK_NAMES.PLOT_TWIST,
    SURVIVOR_PERK_NAMES.REACTIVE_HEALING,
    SURVIVOR_PERK_NAMES.RESURGENCE,
    SURVIVOR_PERK_NAMES.SELF_CARE,
    SURVIVOR_PERK_NAMES.SOLIDARITY,
    SURVIVOR_PERK_NAMES.STRENGTH_IN_SHADOWS,
    SURVIVOR_PERK_NAMES.UNBREAKABLE,
    SURVIVOR_PERK_NAMES.WELL_MAKE_IT,
    SURVIVOR_PERK_NAMES.WERE_GONNA_LIVE_FOREVER
]

TIER_2_BANNED_SURVIVOR_PERK_COMBOS = [
    {'perk1': SURVIVOR_PERK_NAMES.FOR_THE_PEOPLE, 'perk2': SURVIVOR_PERK_NAMES.SECOND_WIND}
]

TIER_2_BANNED_KILLER_PERKS = [
    KILLER_PERK_NAMES.GRIM_EMBRACE
]

TIER_2_BANNED_KILLER_PERK_COMBOS = []