

from dbd_perks.killer_perk_names import KILLER_PERK_NAMES


KILLER_BASE_BANNED_PERKS = [
    KILLER_PERK_NAMES.ALIENT_INSTINCT,
    KILLER_PERK_NAMES.A_NURSES_CALLING,
    KILLER_PERK_NAMES.AWAKENDED_AWARENESS,
    KILLER_PERK_NAMES.BARBEQUE_AND_CHILLI,
    KILLER_PERK_NAMES.BITTER_MURMUR,
    KILLER_PERK_NAMES.COUP_DE_GRACE,
    KILLER_PERK_NAMES.DARKNESS_REVEALED,
    KILLER_PERK_NAMES.DEAD_MANS_SWITCH,
    KILLER_PERK_NAMES.DISCODANCE,
    KILLER_PERK_NAMES.FORCED_HESITATION,
    KILLER_PERK_NAMES.FRIENDS_TIL_THE_END,
    KILLER_PERK_NAMES.GEARDHEAD,
    KILLER_PERK_NAMES.HEX_BLOOD_FAVOR,
    KILLER_PERK_NAMES.HEX_DEVOUR_HOPE,
    KILLER_PERK_NAMES.HEX_FACE_THE_DARKNESS,
    KILLER_PERK_NAMES.HEX_HAUNTED_GROUND,
    KILLER_PERK_NAMES.HEX_NO_ONE_ESCAPES_DEATH,
    KILLER_PERK_NAMES.HEX_NOTHING_BUT_MISERY,
    KILLER_PERK_NAMES.HEX_PENTIMENTO,
    KILLER_PERK_NAMES.HEX_RETRIBUTION,
    KILLER_PERK_NAMES.HEX_WRETECHED_FATE,
    KILLER_PERK_NAMES.HUMAN_GREED,
    KILLER_PERK_NAMES.LANGUID_TOUCH,
    KILLER_PERK_NAMES.LETHAL_PURSUER,
    KILLER_PERK_NAMES.NO_WAY_OUT,
    KILLER_PERK_NAMES.NOWHERE_TO_HIDE,
    KILLER_PERK_NAMES.PLAY_WITH_YOUR_FOOD,
    KILLER_PERK_NAMES.PREDATOR,
    KILLER_PERK_NAMES.SCOURGE_HOOK_FLOODS_OF_RAGE,
    KILLER_PERK_NAMES.SCOURGE_HOOK_HANGMANS_TRICK,
    KILLER_PERK_NAMES.SPIES_FROM_THE_SHADOWS,
    KILLER_PERK_NAMES.STARSTRUCK,
    KILLER_PERK_NAMES.THWACK,
    KILLER_PERK_NAMES.ULTIMATE_WEAPON,
    KILLER_PERK_NAMES.ZANSHIN_TACTICS
]

KILLER_BASE_BANNED_PERK_COMBOS = [
    {'perk1': KILLER_PERK_NAMES.ENDURING, 'perk2': KILLER_PERK_NAMES.HUBRIS},
    {'perk1': KILLER_PERK_NAMES.ENDURING, 'perk2': KILLER_PERK_NAMES.SPIRIT_FURY},
    {'perk1': KILLER_PERK_NAMES.GRIM_EMBRACE, 'perk2': KILLER_PERK_NAMES.SCOURGE_HOOK_PAIN_RESONANCE}
]