

from dbd_perks.survivor_perk_names import SURVIVOR_PERK_NAMES


SURVIVOR_BASE_BANNED_PERKS = [
    SURVIVOR_PERK_NAMES.ALERT,
    SURVIVOR_PERK_NAMES.AUTODIDACT,
    SURVIVOR_PERK_NAMES.BABYSITTER,
    SURVIVOR_PERK_NAMES.BACKGROUND_PLAYER,
    SURVIVOR_PERK_NAMES.BARDIC_INSPIRATION,
    SURVIVOR_PERK_NAMES.BLAST_MINE,
    SURVIVOR_PERK_NAMES.BLOOD_RUSH,
    SURVIVOR_PERK_NAMES.BOON_CIRCLE_OF_HEALING,
    SURVIVOR_PERK_NAMES.BOON_DARK_THEORY,
    SURVIVOR_PERK_NAMES.BOON_EXPONENTIAL,
    SURVIVOR_PERK_NAMES.BOON_ILLUMINATION,
    SURVIVOR_PERK_NAMES.BOON_SHADOW_STEP,
    SURVIVOR_PERK_NAMES.BORROWED_TIME,
    SURVIVOR_PERK_NAMES.BREAKDOWN,
    SURVIVOR_PERK_NAMES.CAMARADERIE,
    SURVIVOR_PERK_NAMES.CHEMICAL_TRAP,
    SURVIVOR_PERK_NAMES.DARK_SENSE,
    SURVIVOR_PERK_NAMES.DETECTIVES_HUNCH,
    SURVIVOR_PERK_NAMES.DRAMATURGY,
    SURVIVOR_PERK_NAMES.EXULTATION,
    SURVIVOR_PERK_NAMES.EYES_OF_BELMONT,
    SURVIVOR_PERK_NAMES.FAST_TRACK,
    SURVIVOR_PERK_NAMES.FOGWISE,
    SURVIVOR_PERK_NAMES.FRIENDLY_COMPETITION,
    SURVIVOR_PERK_NAMES.HARDENED,
    SURVIVOR_PERK_NAMES.HYPERFOCUS,
    SURVIVOR_PERK_NAMES.INVOCATION_TREACHEROUS_CROWS,
    SURVIVOR_PERK_NAMES.INVOCATION_WEAVING_SPIDERS,
    SURVIVOR_PERK_NAMES.KINDRED,
    SURVIVOR_PERK_NAMES.LOW_PROFILE,
    SURVIVOR_PERK_NAMES.LUCKY_BREAK,
    SURVIVOR_PERK_NAMES.OBJECT_OF_OBSESSION,
    SURVIVOR_PERK_NAMES.OFF_THE_RECORD,
    SURVIVOR_PERK_NAMES.OVERZEALOUS,
    SURVIVOR_PERK_NAMES.POTENTIAL_ENERGY,
    SURVIVOR_PERK_NAMES.POWER_STRUGGLE,
    SURVIVOR_PERK_NAMES.PROVE_THYSELF,
    SURVIVOR_PERK_NAMES.QUICK_GAMBIT,
    SURVIVOR_PERK_NAMES.REASSURANCE,
    SURVIVOR_PERK_NAMES.SABOTEUR,
    SURVIVOR_PERK_NAMES.SCENE_PARTNER,
    SURVIVOR_PERK_NAMES.SHOULDER_THE_BURDEN,
    SURVIVOR_PERK_NAMES.SMALL_GAME,
    SURVIVOR_PERK_NAMES.STAKE_OUT,
    SURVIVOR_PERK_NAMES.STILL_SIGHT,
    SURVIVOR_PERK_NAMES.TEAMWORK_POWER_OF_TWO,
    SURVIVOR_PERK_NAMES.TROUBLESHOOTER,
    SURVIVOR_PERK_NAMES.VIGIL,
    SURVIVOR_PERK_NAMES.WICKED,
    SURVIVOR_PERK_NAMES.WIRETAP
]

SURVIVOR_BASE_BANNED_PERK_COMBOS = [
    {'perk1': SURVIVOR_PERK_NAMES.DECISIVE_STRIKE, 'perk2': SURVIVOR_PERK_NAMES.PARENTAL_GUIDANCE}
]