

from dbd_perks.survivor_perk_names import SURVIVOR_PERK_NAMES


SURVIVOR_BASE_BANNED_PERKS = [
    SURVIVOR_PERK_NAMES.ACE_IN_THE_HOLE,
    SURVIVOR_PERK_NAMES.ALERT,
    SURVIVOR_PERK_NAMES.APPOCOLYPTIC_INGENUITY
]