

from dbd_perks.items import SURVIVOR_ITEM_NAMES, SURVIVOR_ITEM_ADD_ON_NAMES
from dbd_perks.killer_perk_names import KILLER_PERK_NAMES
from dbd_perks.maps import MAP_NAMES
from dbd_perks.offerings import KILLER_OFFERING_NAMES, SURVIVOR_OFFERING_NAMES
from dbd_perks.survivor_perk_names import SURVIVOR_PERK_NAMES


class SPIRIT_ADD_ON_NAMES:

    GIFTED_BAMBOO_COMB = "Gifted Bamboo Comb"
    ORIGAMI_CRANE = "Origami Crane"
    SHIWASE_AMULET = "Shiwase Amulet"
    ZORI = "Zori"
    JUNIPER_BONSAI = "Juniper Bonsai"
    KAIUN_TALISMAN = "Kaiun Talisman"
    MUDDY_SPORTS_DAY_CAP = "Muddy Sports Day Cap"
    RINS_BROKEN_WATCH = "Rin's Broken Watch"
    WHITE_HAIR_RIBBON = "White Hair Ribbon"
    KATANA_TSUBA = "Katana Tsuba"
    MOTHERS_GLASSES = "Mother's Glasses"
    RUSTY_FLUTE = "Rusty Flute"
    SENKO_HANABI = "Senko Hanabi"
    UCHIWA = "Uchiwa"
    DRIED_CHERRY_BLOSSOM = "Dried Cherry Blossom"
    FURIN = "Furin"
    WAKIZASHI_SAYA = "Wakizashi Saya"
    YAKUYOKE_AMULET = "Yakuyoke Amulet"
    KINTSUGI_TEACUP = "Kintsugi Teacup"
    MOTHER_DAUGHTER_RING = "Mother-Daughter Ring"


class SPIRIT:

    NAME = "Spirit"

    TIER = 1

    ALL_SURVIVOR_PERKS_BANNED = False

    BANNED_SURVIVOR_PERKS = [
        SURVIVOR_PERK_NAMES.BITE_THE_BULLET,
        SURVIVOR_PERK_NAMES.CHAMPION_OF_LIGHT,
        SURVIVOR_PERK_NAMES.DELIVERANCE,
        SURVIVOR_PERK_NAMES.HOPE,
        SURVIVOR_PERK_NAMES.IRON_WILL,
        SURVIVOR_PERK_NAMES.LIGHTWEIGHT,
        SURVIVOR_PERK_NAMES.PARENTAL_GUIDANCE,
        SURVIVOR_PERK_NAMES.POISED,
        SURVIVOR_PERK_NAMES.RESURGENCE,
        SURVIVOR_PERK_NAMES.SELF_PRESERVATION,
        SURVIVOR_PERK_NAMES.TEAMWORK_COLLECTIVE_STEALTH
    ]

    BANNED_SURVIVOR_PERK_COMBOS = []

    SURVIVOR_OFFERINGS = {
        'offering1': [SURVIVOR_OFFERING_NAMES.SHROUD_OF_BINDING],
        'offering2': [SURVIVOR_OFFERING_NAMES.VIGOS_SHROUD],
        'offering3': [SURVIVOR_OFFERING_NAMES.ANNOTATED_BLUEPRINT],
        'offering4': [SURVIVOR_OFFERING_NAMES.BLOODIED_BLUEPRINT, SURVIVOR_OFFERING_NAMES.TORN_BLUEPRINT]
    }

    SURVIVOR_ITEMS = [
        {
            'item': SURVIVOR_ITEM_NAMES.RANGER_MED_KIT,
            'add_ons': [
                SURVIVOR_ITEM_ADD_ON_NAMES.GEL_DRESSINGS,
                SURVIVOR_ITEM_ADD_ON_NAMES.BANDAGES
            ]
        },
        {
            'item': SURVIVOR_ITEM_NAMES.SPORT_FLASHLIGHT,
            'add_ons': [
                SURVIVOR_ITEM_ADD_ON_NAMES.BATTERY,
                SURVIVOR_ITEM_ADD_ON_NAMES.LEATHER_GRIP,
                SURVIVOR_ITEM_ADD_ON_NAMES.POWER_BULB,
                SURVIVOR_ITEM_ADD_ON_NAMES.WIDE_LENS
            ]
        },
        {
            'item': SURVIVOR_ITEM_NAMES.CHINESE_FIRECRACKER,
            'add_ons': []
        }
    ]

    BANNED_KILLER_PERKS = [
        KILLER_PERK_NAMES.HUBRIS
    ]

    BANNED_KILLER_PERKS_COMBOS = []

    ALL_KILLER_ADD_ONS = []

    BANNED_KILLER_ADD_ONS = [
        SPIRIT_ADD_ON_NAMES.DRIED_CHERRY_BLOSSOM,
        SPIRIT_ADD_ON_NAMES.FURIN,
        SPIRIT_ADD_ON_NAMES.MOTHER_DAUGHTER_RING,
        SPIRIT_ADD_ON_NAMES.WAKIZASHI_SAYA,
        SPIRIT_ADD_ON_NAMES.YAKUYOKE_AMULET
    ]

    KILLER_OFFERINGS = [KILLER_OFFERING_NAMES.CUT_COIN]

    MAP_1 = MAP_NAMES.WRECKERS_YARD
    MAP_2 = MAP_NAMES.GRIM_PANTRY
    MAP_3 = MAP_NAMES.DEAD_DAWG_SALOON
