

from dbd_perks.killer_perk_names import KILLER_PERK_NAMES
from dbd_perks.survivor_perk_names import SURVIVOR_PERK_NAMES


class SPIRIT:

    NAME = "Spirit"

    TIER = 1

    BANNED_SURVIVOR_PERKS = [
        SURVIVOR_PERK_NAMES.BITE_THE_BULLET,
        SURVIVOR_PERK_NAMES.CHAMPION_OF_LIGHT,
        SURVIVOR_PERK_NAMES.DELIVERANCE,
        SURVIVOR_PERK_NAMES.HOPE,
        SURVIVOR_PERK_NAMES.IRON_WILL,
        SURVIVOR_PERK_NAMES.LIGHTWEIGHT,
        SURVIVOR_PERK_NAMES.PARENTAL_GUIDANCE,
        SURVIVOR_PERK_NAMES.POISED,
        SURVIVOR_PERK_NAMES.RESURGENCE,
        SURVIVOR_PERK_NAMES.SELF_PRESERVATION,
        SURVIVOR_PERK_NAMES.TEAMWORK_COLLECTIVE_STEALTH
    ]

    BANNED_KILLER_PERKS = [
        KILLER_PERK_NAMES.HUBRIS
    ]
